version: "3.8"

services:
  fletbot:
    build: .
    container_name: fletbot
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fletbot.rule=Host(`painel.n8nautomatic.com`)"
      - "traefik.http.routers.fletbot.entrypoints=websecure"
      - "traefik.http.routers.fletbot.tls.certresolver=myresolver"
      - "traefik.http.services.fletbot.loadbalancer.server.port=8550"
    networks:
      - traefik

networks:
  traefik:
    external: true

