services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: always
    volumes:
      - ./store:/app/store
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whatsapp-bot.rule=Host(`bot.n8nautomatic.com`)"
      - "traefik.http.routers.whatsapp-bot.entrypoints=websecure"
      - "traefik.http.routers.whatsapp-bot.tls.certresolver=myresolver"
      - "traefik.http.services.whatsapp-bot.loadbalancer.server.port=3001"
    networks:
      - traefik
